"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh';

export const translations = {
    en: {
        // Nav / Landing
        launchDapp: 'LAUNCH DAPP',
        readTheDocs: 'READ THE DOCS',
        backToHome: 'BACK',
        protocolDocs: 'Protocol Docs',
        // Hero
        heroTitle: 'THE MARKET NEVER SLEEPS.',
        heroDesc: 'SMC AI is a brutal quantitative trading engine powered exclusively by OpenClaw. We map on-chain liquidity, run xAI sentiment analysis, and execute institutional-grade Smart Money Concepts (SMC) strategies before retail markets even react.',
        // How it works
        howItWorks: 'THE ARCHITECTURE',
        howItWorksDesc: 'The architecture behind the SMC AI ecosystem.',
        archS1Title: 'Data Ingestion',
        archS1Desc: 'We track millions of on-chain data points per second. Wallet tracking, DEX liquidity pools, and Mempool activity are ingested into the core in real-time.',
        archS2Title: 'SMC Processing',
        archS2Desc: 'The OpenClaw Agent applies Smart Money Concepts to raw data — mapping Order Blocks, Fair Value Gaps, and liquidity sweeps.',
        archS3Title: 'Zero-Latency Execution',
        archS3Desc: 'Trades executed directly via private RPC nodes, bypassing public mempool front-running for precise price fills.',
        flowStep1Title: 'MEMPOOL STREAM INGESTION',
        flowStep1Desc: 'OpenClaw Engine subscribes to a high-bandwidth, private mempool stream, receiving unconfirmed transactions in real-time — before they hit a public block.',
        flowStep2Title: 'SMC STRUCTURAL ANALYSIS',
        flowStep2Desc: 'The engine scans for institutional footprints: Fair Value Gaps, Order Blocks, ChoCH patterns, and Liquidity Sweeps — all computed natively in TypeScript with sub-millisecond precision.',
        flowStep3Title: 'xAI SENTIMENT CROSS-CHECK',
        flowStep3Desc: 'Before committing to a trade, each signal is cross-validated against xAI\'s live social sentiment graph, filtering out noise from market manipulation events.',
        flowStep4Title: 'AUTONOMOUS SMART EXECUTION',
        flowStep4Desc: 'Upon signal confirmation, OpenClaw executes the trade via the Sentinel Vault smart contract — gasless for users, with hardware-level precision on entry price.',
        // Terminal section
        signalAnalysis: 'SIGNAL ANALYSIS',
        executionConfirmed: 'EXECUTION CONFIRMED',
        intelTitle: 'Intelligence that',
        intelAccent: 'acts.',
        intelDesc: 'Unlike simple indicator bots, OpenClaw understands the market like an institutional trader. It reads Smart Money Concepts, hunting for Fair Value Gaps and Order Block mitigations, while simultaneously verifying mass psychology via xAI.',
        intelList1: 'SMC Structure Detection (CHoCH, FVG, OB)',
        intelList2: 'xAI Algorithmic Sentiment Analysis',
        intelList3: 'Absolute Trade Management (TP/SL)',
        // Ecosystem section
        ecosystem: 'INSTITUTIONAL ECOSYSTEM',
        ecosystemDesc: 'A fully integrated stack purpose-built for institutional-grade capital deployment.',
        aiAgentTitle: 'AI Autonomous Agent',
        aiAgentDesc: 'The OpenClaw Engine autonomously scans the BSC mempool, identifies institutional SMC patterns, then executes trades via a non-custodial smart contract vault.',
        dashboardTitle: 'Live Portfolio Dashboard',
        dashboardDesc: 'Monitor your portfolio metrics, running PNL, and active OpenClaw algorithmic positions across all connected smart-contracts.',
        bscTradingTitle: 'BSC Trading / Swap',
        bscTradingDesc: 'Instant on-chain settlement matrix. Route massive volume via our internal 1inch aggregation node with 0 slippage tolerance.',
        // Stats 
        autonomousPrecision: 'Autonomous Precision.',
        autonomousDesc: 'The OpenClaw neural net doesn\'t just analyze. It executes flawlessly based on precise SMC methodology and xAI sentiment checks.',
        stat1Desc: 'Backtested across 10,000+ simulation pairs using Smart Money Concepts logic.',
        stat2Desc: 'Instant entries upon CHoCH and Order Block mitigation. Bypassing RPC memory pools.',
        stat3Desc: 'Aggregates global Twitter/X sentiment on every asset, aligning social bias with SMC structures.',
        // Marquee
        mq1: 'LATEST UPDATES FROM THE NEW MECHANISMS',
        mq2: 'OPENCLAW V2: ADVANCED TRAILING STOP ACTIVE',
        mq3: '0MS LATENCY SMC EXECUTION ROUTING',
        mq4: 'xAI SENTIMENT SCALPING ONLINE',
        // Footer
        footerCopy: '© 2026 SMC AI. Powered by OpenClaw Engine.',
        footerDisclaimer: 'Trading crypto involves extreme risk. Manage your capital ruthlessly. Not financial advice.',
        // Settings
        settings: 'Settings',
        theme: 'Theme',
        darkMode: 'Dark',
        lightMode: 'Light',
        language: 'Language',
        // Dashboard Sidebar
        dashboard: 'Dashboard',
        aiAgent: 'AI Agent',
        bscTrading: 'BSC Trading',
        vault: 'Vault',
        futures: 'Futures',
        riskPersona: 'RISK PERSONA ↻',
        conservative: 'CONSERVATIVE',
        balanced: 'BALANCED',
        aggressive: 'AGGRESSIVE',
        // Docs
        docsTitle: 'SMC AI ARCHITECTURE',
        docsIntro1: 'Welcome to the core documentation of the SMC AI trading infrastructure. This repository of knowledge is designed to provide complete transparency into our proprietary quantitative methodologies. Here, you will discover how the OpenClaw Engine systematically decodes institutional Smart Money Concepts (SMC) to map out high-probability market structures in real-time.',
        docsIntro2: 'By merging deep on-chain mempool analysis with advanced xAI-driven social sentiment verification, our architecture removes human emotional bias from trading. Our ultimate goal is to provide retail participants with decentralized, non-custodial access to institutional-grade execution capabilities, leveling the playing field against predatory algorithms and high-frequency trading firms.',
        docsS1Title: '1. The OpenClaw Core',
        docsS1P1: 'At the heart of the ecosystem lies the OpenClaw Agent, a highly optimized, asynchronous state machine built strictly for on-chain quantitative analysis. Unlike standard trading bots that rely on lagging retail indicators (like RSI or MACD), OpenClaw ingests raw mempool events, decoding block-by-block liquidity movements to construct a high-fidelity map of the market\'s true structural intent.',
        docsS1CodeTitle: 'OpenClaw Memory Initialization',
        docsS2Title: '2. Smart Money Concepts',
        docsS2P1: 'The OpenClaw engine translates human-centric visual SMC methodologies into rigorous mathematical algorithms. It scans specifically for the footprints of institutional capital, allowing the agent to enter positions precisely where large-scale market participants accumulate.',
        docsS2FvgTitle: 'Fair Value Gaps (FVG)',
        docsS2FvgDesc: 'Identifies algorithmic price imbalances between consecutive candles where aggressive institutional momentum leaves liquidity voids.',
        docsS2ObTitle: 'Order Blocks (OB)',
        docsS2ObDesc: 'Locates the final bearish or bullish candle prior to a massive impulse move, marking institutional mitigation zones for exact, low-drawdown entries.',
        docsS2LiqTitle: 'Liquidity Sweeps (BSL/SSL)',
        docsS2LiqDesc: 'Detects when retail stop-losses are triggered above swing highs (Buy-side) or swing lows (Sell-side), recognizing the manipulation phase preceding a reversal.',
        docsS3Title: '3. xAI Social Verification',
        docsS3P1: 'Technical structure alone is insufficient in highly volatile, momentum-driven markets. Before any SMC trade thesis is approved for execution, OpenClaw queries the xAI Network to sample vast amounts of unstructured social data from X (formerly Twitter).',
        docsS3P2: 'The xAI language models process real-time tweet volumes, influencer sentiment shifts, and narrative momentum scores. If the technical SMC setup signals a long position, but xAI detects a severe, coordinated bearish narrative emerging on social channels, the engine will invalidate the setup and protect the capital. This dual-layer validation radically reduces false breakouts.',
        docsS3CodeTitle: 'xAI Sentiment Query Log',
        docsS4Title: '4. 1inch Aggregation',
        docsS4P1: 'Trade execution cannot suffer from slippage or poor liquidity. When OpenClaw issues a verified trade command, the protocol seamlessly hands off the payload to the 1inch Aggregation Router.',
        docsS4P2: 'By iterating over dozens of decentralized exchanges (DEXs) simultaneously, the 1inch protocol constructs the most capital-efficient routing path. It splits single orders across multiple liquidity pools, avoiding high price-impact trades and securing institutional-grade execution rates that standalone DEX interfaces cannot match.',
        docsS4SlipTitle: 'SLIPPAGE PROTECTION',
        docsS4SlipDesc: 'Dynamic Auto-Ranging',
        docsS4LiqTitle: 'LIQUIDITY DEEP SCAN',
        docsS4LiqDesc: '90+ DEX Protocols',
        docsS5Title: '5. Vault System & Audit',
        docsS5P1: 'User capital is secured within the SMC Vault, a fortified on-chain pooling contract engineered for non-custodial, high-frequency protocol engagement. The vault guarantees isolated balance tracking per user while providing aggregate liquidity for the Agent to execute institutional-scale swaps.',
        docsS5P2: 'The OpenClaw Agent is granted strictly limited `TRADER_ROLE` permissions. It can route funds through whitelisted aggregators (like 1inch) for profit realization, but it mathematically cannot withdraw or transfer your base capital. Only the depositor retains the cryptographic right to execute withdrawals.',
        docsS5AuditTitle: 'Contract Audit Status',
        docsS5Audit1Title: 'SECURITY AUDIT',
        docsS5Audit1Desc: 'PASSED (v1.0.0)',
        docsS5Audit2Title: 'FUNDS CUSTODY',
        docsS5Audit2Desc: '100% NON-CUSTODIAL',
        docsS5Audit3Title: 'AGENT CLEARANCE',
        docsS5Audit3Desc: 'TRADE-ONLY ROLE',
        docsS6Title: '6. Institutional Risk Management',
        docsS6P1: 'Capital preservation is the ultimate priority of the OpenClaw Engine. To ensure the Vault is never drained by adverse volatility or liquidation cascades, every automated execution enforces strict institutional risk parameters constraints.',
        docsS6P2: 'For all ApolloX Perpetual Futures operations, the Agent strictly utilizes Isolated Margin. The automated Stop-Loss (SL) is dynamically calculated such that a position is closed exactly when the unrealized PNL reaches the value of the open position margin (-100% ROE), completely preventing cross-margin contagions. For BSC Swaps, a tight structure-based SL is algorithmically defined to preserve base capital.',
        // Dashboard
        bscWhaleTracker: 'BSC Whale Tracker',
        scanningChain: 'Scanning chain...',
        recentTransfers: 'recent large transfers',
        refresh: 'Refresh',
        smartMoneyRadar: 'Smart Money Radar',
        lastUpdated1h: 'Last updated: {time} • BSC 1H Volume',
        scanMarket: 'Scan Market',
        scanning: 'Scanning...',
        vol: 'Vol: ${vol}M • Score: {score}/100',
        aiAgentQuickPanel: 'AI Agent',
        active: 'Active',
        agentGreeting: '"Greetings! I am your SMC Capital Manager Agent. I autonomously monitor on-chain liquidity, execute precision trades, and safeguard your portfolio using advanced Smart Money Concepts. I\'m currently detecting massive liquidity shifts on BSC Top 50 pairs. How can I assist you with your capital allocation today?"',
        pendingSignals: 'Pending Signals',
        buying: 'BUYING',
        execSniper: 'Executing sniper via 1inch. 95% Confidence.',
        openFullAiTerminal: 'Open Full AI Terminal',
        topBscTargetPools: 'Top BSC Target Pools',
        oracleNode: 'Oracle Node',
        pair: 'Pair',
        action: 'Action',
        trade: 'TRADE',
        scanningNetworkData: 'Scanning network data...',
        newPairsEscrow: 'New Pairs Escrow',
        highRiskDesignation: '⚠ High Risk Designation',
        highRiskWait: 'New pairs have extreme volatility. Trading unverified smart contracts risks total capital loss. Always verify CA before routing.',
        scanningNewDeployments: 'Scanning new deployments...',
        totalEstBalance: 'Total Estimated Balance',
        livePnl: 'Live PnL',
        // Futures
        comingSoonTitle: 'COMING SOON',
        comingSoonDesc: 'SMC AI Perpetual Futures Terminal is currently under development.',
        interactiveChart: 'Interactive Chart',
        tvPlaceholder: 'TradingView Advanced Chart for {coin}-PERP\n(TV Widget Integration Placeholder)',
        l2Orderbook: 'L2 Orderbook',
        priceUsdc: 'Price (USDC)',
        size: 'Size ({coin})',
        marketTrades: 'Market Trades',
        time: 'Time',
        futuresTitle: 'ApolloX Perpetual Futures',
        searchPairPlaceholder: 'Search pair (e.g. BTCUSDT)...',
        leverageMax: 'Max Leverage',
        isolatedMargin: 'Isolated',
        crossMargin: 'Cross',
        liquidationPrice: 'Est. Liq. Price',
        estFees: 'Est. Trade Fees',
        openLong: 'OPEN LONG',
        openShort: 'OPEN SHORT',
        posSize: 'Position Size',
        futuresBalance: 'Futures Bal:',
        orderblockDetected: 'Orderblock Detected',
        
        // Share PNL
        sharePnlTitle: 'SHARE POSITION',
        hidePositionSize: 'Hide Position Size',
        downloadPng: 'Download PNG',
        shareTwitter: 'Share to X',
        shareTelegram: 'Share to Telegram',
        entryPrice: 'Entry Price',
        markPrice: 'Mark Price',
        roe: 'ROE %',
        scanToVerify: 'Scan to verify on SMC-AI.io',
        
        // Trade AI Agent
        tradeAgentGreeting1: 'Greetings. I am your **SMC Agent** — your dedicated Capital Manager for Binance Smart Chain. I have been synchronized with your wallet on the Binance Smart Chain. Detected Balance: **{bal} BNB** \u26a1\n\nI actively monitor on-chain volume, detect institutional liquidity sweeps, and execute advanced Smart Money Concepts natively. {marketUpdate}\n\nWhich sector or pair shall we allocate capital to today?',
        tradeAgentGreeting2: 'Greetings. I am your **SMC Agent** — your dedicated Capital Manager for Binance Smart Chain. Wallet synchronized. Detected Balance: **{bal} BNB** \u26a1\n\nI monitor on-chain volume, detect liquidity sweeps, and execute advanced SMC logic. Which pair shall we dominate today?',
        marketUpdateActive: 'Markets look interesting today. ',
        marketUpdateTrending: 'Top trending right now: **{top3}**. ',
        typeMessagePlaceholder: 'Type a message or paste a contract address...',
        analyzing: 'Analyzing...',
        send: 'Send',
        walletNotConnected: 'Wallet Not Connected',
        connectWalletPrompt: 'Please connect your wallet to use the SMC Agent.',
        examplesTitle: 'Try asking:',
        example1: '"Snipe 0.1 BNB of the newest pump.fun pool"',
        example2: '"Scan for FVG setups on Top 10 BSC pairs"',
        example3: '"What\'s the current xAI sentiment for $SOL?"',
        tradeExecutedTitle: 'TRADE EXECUTED',
        symbolLabel: 'Symbol:',
        sideLabel: 'Side:',
        sizeLabel: 'Size:',
        entryLabel: 'Entry:',
        slLabel: 'SL:',
        tpLabel: 'TP:',
        confidenceLabel: 'Confidence:',
        viewOnExplorer: 'View on Explorer',
        // Trade BSC Swap
        tradeBscTitle: 'BSC Trading / Swap',
        chartProviderCustom: 'TradingView (Top Pairs)',
        chartProviderGecko: 'GeckoTerminal (Any CA)',
        enterContractAddress: 'Enter token contract address...',
        loadChart: 'Load Chart',
        insufficientBalance: 'Insufficient Vault Balance!',
        installMetaMask: 'Please install MetaMask to execute swaps.',
        swapFailed: 'Swap Failed: ',
        swapPanelTitle: 'OpenClaw Swap Matrix',
        payAmount: 'Amount to Pay',
        balanceLabel: 'Vault Bal:',
        maxLabel: 'MAX',
        receiveAmount: 'Amount to Receive (Est.)',
        slippageTolerance: 'Slippage Tolerance',
        autoSlippageSelected: 'Auto slippage applied based on MEV risk.',
        executeSwap: 'EXECUTE SWAP',
        executing: 'EXECUTING...',
        approveWallet: 'Approve in Wallet',
        swapSuccess: 'Swap Successful!',
        gasFee: 'Gas Fee',
        gasCalculated: '~0.001 BNB (Gasless in Vault V2)',
        routing: 'Routing',
        routingValue: '1inch Aggregator',
    },
    zh: {
        // Nav / Landing
        launchDapp: '启动 DAPP',
        readTheDocs: '阅读文档',
        backToHome: '返回',
        protocolDocs: '协议文档',
        // Hero
        heroTitle: '市场永不眠。',
        heroDesc: 'SMC AI 是一款由 OpenClaw 独家驱动的激进量化交易引擎。我们在零售市场反应之前，完成链上流动性映射、xAI 情绪分析，并执行机构级智能资金概念（SMC）策略。',
        // How it works
        howItWorks: '架构体系',
        howItWorksDesc: 'SMC AI 生态系统背后的核心架构。',
        archS1Title: '数据摄取',
        archS1Desc: '我们每秒追踪数百万个链上数据点。钱包追踪、DEX 流动性池和内存池活动被实时摄取到核心系统中。',
        archS2Title: 'SMC 处理',
        archS2Desc: 'OpenClaw 代理将聪明钱概念（SMC）应用于原始数据 —— 映射订单块、公允价值缺口和流动性扫荡。',
        archS3Title: '零延迟执行',
        archS3Desc: '交易通过私有 RPC 节点直接执行，绕过公共内存池的抢跑，实现精准的价格成交。',
        flowStep1Title: '内存池流数据接入',
        flowStep1Desc: 'OpenClaw 引擎订阅高带宽私有内存池流，实时接收未经确认的交易数据——早于公链区块打包。',
        flowStep2Title: 'SMC 结构分析',
        flowStep2Desc: '引擎扫描机构资金足迹：公允价值缺口（FVG）、订单块（OB）、结构变化（ChoCH）模式及流动性扫荡——全部以 TypeScript 原生计算，精度达亚毫秒级。',
        flowStep3Title: 'xAI 情绪二次验证',
        flowStep3Desc: '在下单前，每个信号都通过 xAI 的实时社交情绪图谱进行交叉验证，过滤市场操纵噪音。',
        flowStep4Title: '自主智能执行',
        flowStep4Desc: '信号确认后，OpenClaw 通过 Sentinel Vault 智能合约执行交易——用户无需支付 Gas，入场精度达到硬件级别。',
        // Terminal section
        signalAnalysis: '信号分析',
        executionConfirmed: '执行确认',
        intelTitle: '会行动的',
        intelAccent: '机器智能。',
        intelDesc: '不同于简单的指标机器人，OpenClaw 像机构交易员一样理解市场。它解读智能资金概念 (SMC)，捕捉公允价值缺口 (FVG) 和订单块缓解位置，同时通过 xAI 验证大众心理学。',
        intelList1: 'SMC 结构检测 (CHoCH, FVG, OB)',
        intelList2: 'xAI 算法社交情绪分析',
        intelList3: '绝对的交易管理 (TP/SL)',
        // Ecosystem section
        ecosystem: '机构生态系统',
        ecosystemDesc: '专为机构级资本部署而打造的全栈集成系统。',
        aiAgentTitle: 'AI 自主智能体',
        aiAgentDesc: 'OpenClaw 引擎自主扫描 BSC 内存池，识别机构 SMC 模式，并通过非托管智能合约金库完成交易执行。',
        dashboardTitle: '实时投资组合看板',
        dashboardDesc: '监控您的投资组合指标、实时盈亏及所有已连接智能合约上的 OpenClaw 算法持仓。',
        bscTradingTitle: 'BSC 交易 / 兑换',
        bscTradingDesc: '即时链上结算矩阵。通过我们内部的 1inch 聚合节点进行大额交易，零滑点容忍。',
        // Stats
        autonomousPrecision: '自动化高精度执行',
        autonomousDesc: 'OpenClaw 神经网络不仅进行分析。它基于精确的 SMC 方法论和 xAI 情绪检查，实现完美无暇的自动化执行。',
        stat1Desc: '使用智能资金概念 (SMC) 逻辑在超过 10,000 个模拟交易对上进行回测。',
        stat2Desc: '在特性改变 (CHoCH) 和订单块缓解时立即执行入场。完全绕过 RPC 内存池。',
        stat3Desc: '汇总所有资产的全球 Twitter/X 实时社交情绪，将社交叙事倾向与 SMC 技术结构对齐。',
        // Marquee
        mq1: '新机制的最新更新',
        mq2: 'OPENCLAW V2：高级追踪止损已激活',
        mq3: '0 毫秒延迟 SMC 执行路由',
        mq4: 'xAI 情绪剥头皮交易上线',
        // Footer
        footerCopy: '© 2026 SMC AI。由 OpenClaw 引擎驱动。',
        footerDisclaimer: '加密货币交易风险极高，请严格管理您的资金。本内容不构成投资建议。',
        // Settings
        settings: '设置',
        theme: '主题',
        darkMode: '深色',
        lightMode: '浅色',
        language: '语言',
        // Dashboard Sidebar
        dashboard: '仪表盘',
        aiAgent: 'AI 智能体',
        bscTrading: 'BSC 交易',
        vault: '金库',
        futures: '期货',
        riskPersona: '风险模式 ↻',
        conservative: '保守',
        balanced: '平衡',
        aggressive: '激进',
        // Docs
        docsTitle: 'SMC AI 架构',
        docsIntro1: '欢迎来到 SMC AI 交易基础设施的核心文档。本知识库旨在对我们的专有量化方法论提供完全透明的说明。在这里，您将了解 OpenClaw 引擎如何系统性地解码机构级智能资金概念（SMC），以实时绘制高概率市场结构图。',
        docsIntro2: '通过将深度链上内存池分析与先进的 xAI 驱动社交情绪验证相结合，我们的架构彻底消除了交易中的人为情绪偏差。我们的终极目标是为零售参与者提供去中心化、非托管的机构级执行能力，以对抗捕食性算法和高频交易公司，让竞争更加公平。',
        docsS1Title: '1. OpenClaw 核心',
        docsS1P1: '位于生态系统核心的是 OpenClaw 智能体，这是一个高度优化的异步状态机，专门为链上量化分析而构建。与依赖滞后的零售指标（如 RSI 或 MACD）的标准交易机器人不同，OpenClaw 摄取原始内存池事件，逐块解码流动性变动，以构建反映市场真实意图的高保真结构图。',
        docsS1CodeTitle: 'OpenClaw 内存初始化',
        docsS2Title: '2. 智能资金概念（SMC）',
        docsS2P1: 'OpenClaw 引擎将以人为中心的视觉 SMC 方法论转化为严格的数学算法。它专门寻找机构资本的足迹，让智能体能够在大型市场参与者吸筹的精确位置进场。',
        docsS2FvgTitle: '公允价值缺口（FVG）',
        docsS2FvgDesc: '识别连续K线之间算法导致的价格失衡，此时激进的机构动量会留下流动性真空。',
        docsS2ObTitle: '订单块（OB）',
        docsS2ObDesc: '定位在大规模脉冲式移动之前的最后一根阴线或阳线，标记出机构的吸筹区，以实现精确的低回撤入场。',
        docsS2LiqTitle: '流动性扫荡（BSL/SSL）',
        docsS2LiqDesc: '检测何时在波段高点（买方）或波段低点（卖方）上方触发零售止损，识别出逆转前的操纵阶段。',
        docsS3Title: '3. xAI 社交情绪验证',
        docsS3P1: '在高度波动、受动量驱动的市场中，仅仅依靠技术结构是不够的。在任何 SMC 交易策略获批执行之前，OpenClaw 都会查询 xAI 网络，从 X（原 Twitter）上采集海量的非结构化社交数据。',
        docsS3P2: 'xAI 语言模型实时处理推文量、意见领袖情绪转变和叙事动量得分。如果技术面的 SMC 信号显示做多，但 xAI 在社交渠道中检测到强烈且协同的看跌叙事正在形成，该引擎就会使该信号失效以保护资金。这种双层验证极大减少了假突破。',
        docsS3CodeTitle: 'xAI 情绪查询日志',
        docsS4Title: '4. 1inch 聚合交易',
        docsS4P1: '交易执行不应遭受滑点或低流动性的影响。当 OpenClaw 发出一个经过验证的交易指令时，协议会无缝地将负载移交给 1inch 聚合路由器。',
        docsS4P2: '通过同时遍历数十个去中心化交易所（DEX），1inch 协议构建了资金效率最高的路由路径。它将单笔大订单分散到多个流动性池中，避免了高价格冲击（Price Impact）的交易，确保了单一 DEX 界面无法匹配的机构级执行费率。',
        docsS4SlipTitle: '滑点保护',
        docsS4SlipDesc: '动态自动测距',
        docsS4LiqTitle: '深度流动性扫描',
        docsS4LiqDesc: '90+ DEX 协议',
        docsS5Title: '5. 金库系统与审计',
        docsS5P1: '用户资金被保护在 SMC 金库（Vault）中，这是一个强大且经过强化的链上池化合约，专为非托管、高频率的协议交互而设计。该金库保证了每个用户的独立余额跟踪，同时为智能体执行机构级规模的兑换提供总流动性。',
        docsS5P2: 'OpenClaw 智能体仅被授予严格限制的 `TRADER_ROLE` 权限。它可以将资金通过白名单聚合器（如 1inch）进行交易以实现利润，但它在数学上不可能提取或转移您的本金。只有存款人保留执行提款的密码学权利。',
        docsS5AuditTitle: '智能合约审计状态',
        docsS5Audit1Title: '安全审计',
        docsS5Audit1Desc: '已通过 (v1.0.0)',
        docsS5Audit2Title: '资金托管',
        docsS5Audit2Desc: '100% 非托管',
        docsS5Audit3Title: '智能体权限',
        docsS5Audit3Desc: '仅限交易',
        docsS6Title: '6. 机构级风险管理',
        docsS6P1: '资本保全是 OpenClaw 引擎的最终优先级。为了确保金库资金永远不会因极端波动或连环清算而枯竭，所有的自动交易执行都强制要求遵守严格的机构级风险参数约束。',
        docsS6P2: '对于所有的 ApolloX 永续合约操作，智能体严格采用逐仓模式 (Isolated Margin)。自动止损 (SL) 的动态计算方式为：当未实现盈亏达到开仓保证金的价值（即回报率达 -100%）时，该仓位将被精确关闭，这彻底防止了全仓风险蔓延。对于 BSC 现货兑换，系统会在算法层面基于市场结构设定紧密的止损线，以保护核心本金。',
        // Dashboard
        bscWhaleTracker: 'BSC 巨鲸追踪器',
        scanningChain: '正在扫描链上数据...',
        recentTransfers: '笔近期大额转账',
        refresh: '刷新',
        smartMoneyRadar: '聪明的钱（Smart Money）雷达',
        lastUpdated1h: '最后更新: {time} • BSC 1小时交易量',
        scanMarket: '扫描市场',
        scanning: '扫描中...',
        vol: '量: ${vol}M • 评分: {score}/100',
        aiAgentQuickPanel: 'AI 智能体',
        active: '活跃',
        agentGreeting: '"您好！我是您的 SMC 资本管理智能体。我通过使用高级 Smart Money Concepts 自主监控链上流动性、执行精准交易并保护您的投资组合。我目前监测到 BSC 前 50 大交易对出现巨大的流动性变动。今天我可以如何协助您进行资金配置？"',
        pendingSignals: '待处理信号',
        buying: '正在买入',
        execSniper: '正在通过 1inch 执行狙击。置信度 95%。',
        openFullAiTerminal: '打开完整 AI 终端',
        topBscTargetPools: 'BSC 热门目标池',
        oracleNode: '预言机节点',
        pair: '交易对',
        action: '操作',
        trade: '交易',
        scanningNetworkData: '正在扫描网络数据...',
        newPairsEscrow: '新交易对监控池',
        highRiskDesignation: '⚠ 高风险指示',
        highRiskWait: '新交易对伴随极高波动性。交易未经审计的智能合约可能导致本金完全损失。在路由前，请务必核实合约地址。',
        scanningNewDeployments: '正在扫描新部署的合约...',
        totalEstBalance: '总估算余额',
        livePnl: '实时盈亏',
        // Futures
        comingSoonTitle: '敬请期待',
        comingSoonDesc: 'SMC AI 永续合约终端目前正在开发中。',
        interactiveChart: '交互式图表',
        tvPlaceholder: 'TradingView {coin}-PERP 高级图表\n(TV 组件集成占位符)',
        l2Orderbook: 'L2 订单薄',
        priceUsdc: '价格 (USDC)',
        size: '数量 ({coin})',
        marketTrades: '市场交易',
        time: '时间',
        futuresTitle: 'ApolloX 永续合约',
        searchPairPlaceholder: '搜索交易对 (如 BTCUSDT)...',
        leverageMax: '最大杠杆',
        isolatedMargin: '逐仓',
        crossMargin: '全仓',
        liquidationPrice: '预估强平价',
        estFees: '预估交易费',
        openLong: '开多',
        openShort: '开空',
        posSize: '持仓规模',
        futuresBalance: '合约余额:',
        orderblockDetected: '检测到订单块',
        
        // Share PNL
        sharePnlTitle: '分享仓位',
        hidePositionSize: '隐藏持仓规模',
        downloadPng: '下载图片 (PNG)',
        shareTwitter: '分享至 X',
        shareTelegram: '分享至 Telegram',
        entryPrice: '开仓均价',
        markPrice: '标记价格',
        roe: '回报率 (ROE) %',
        scanToVerify: '在 SMC-AI.io 上扫描验证',
        
        // Trade AI Agent
        tradeAgentGreeting1: '您好。我是您的 **SMC 智能体** — 您在币安智能链上的专属资本管理器。我已与您的 BSC 钱包同步。检测到余额：**{bal} BNB** \u26a1\n\n我主动监控链上交易量，检测机构流动性扫荡，并原生执行高级 Smart Money Concepts。{marketUpdate}\n\n今天我们要将资金分配到哪个板块或交易对？',
        tradeAgentGreeting2: '您好。我是您的 **SMC 智能体** — 您在币安智能链上的专属资本管理器。钱包已同步。检测到余额：**{bal} BNB** \u26a1\n\n我监控链上交易量，检测流动性扫荡，并执行高级 SMC 逻辑。今天我们要主导哪个交易对？',
        marketUpdateActive: '今天市场看起来很有趣。',
        marketUpdateTrending: '当前最热门的代币：**{top3}**。',
        typeMessagePlaceholder: '输入消息或粘贴合约地址...',
        analyzing: '分析中...',
        send: '发送',
        walletNotConnected: '钱包未连接',
        connectWalletPrompt: '请连接您的钱包以使用 SMC 智能体。',
        examplesTitle: '尝试提问：',
        example1: '"狙击 0.1 BNB 的最新 pump.fun 池"',
        example2: '"扫描 BSC 前 10 名交易对的 FVG 设置"',
        example3: '"$SOL 当前的 xAI 情绪如何？"',
        tradeExecutedTitle: '交易已执行',
        symbolLabel: '交易对:',
        sideLabel: '方向:',
        sizeLabel: '数量:',
        entryLabel: '入场价:',
        slLabel: '止损:',
        tpLabel: '止盈:',
        confidenceLabel: '置信度:',
        viewOnExplorer: '在区块链浏览器上查看',
        // Trade BSC Swap
        tradeBscTitle: 'BSC 交易 / 兑换',
        chartProviderCustom: 'TradingView (热门交易对)',
        chartProviderGecko: 'GeckoTerminal (任意合约)',
        enterContractAddress: '输入代币合约地址...',
        loadChart: '加载图表',
        insufficientBalance: '金库余额不足！',
        installMetaMask: '请安装 MetaMask 以执行兑换。',
        swapFailed: '兑换失败：',
        swapPanelTitle: 'OpenClaw 兑换矩阵',
        payAmount: '支付数量',
        balanceLabel: '金库余额:',
        maxLabel: '最大',
        receiveAmount: '接收数量 (预估)',
        slippageTolerance: '滑点容忍度',
        autoSlippageSelected: '已根据 MEV 风险应用自动滑点。',
        executeSwap: '执行兑换',
        executing: '执行中...',
        approveWallet: '在钱包中确认',
        swapSuccess: '兑换成功！',
        gasFee: 'Gas 费',
        gasCalculated: '~0.001 BNB (在 V2 金库中免 Gas)',
        routing: '路由节点',
        routingValue: '1inch 聚合器',
    }
};

type Translations = typeof translations['en'];

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
    lang: 'en',
    setLang: () => { },
    t: translations.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLangState] = useState<Language>('en');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        const saved = localStorage.getItem('smc-lang') as Language | null;
        if (saved && (saved === 'en' || saved === 'zh')) {
            setLangState(saved);
        }
        setMounted(true);
    }, []);

    const setLang = (l: Language) => {
        setLangState(l);
        localStorage.setItem('smc-lang', l);
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
            <div key={mounted ? 'mounted' : 'server'} style={{ display: 'contents' }}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
